In [1]:
from data_parser import parse_csv, enum_classes
from nn_layers import input_layer, hidden_layer, output_layer
from neural_network import nn
import numpy as np

In [2]:
x = parse_csv('train.x.csv', 1, 27)

In [3]:
l = input_layer(x[0:1])

In [4]:
l.get_signal().shape

(27, 1)

In [5]:
x.shape

(13000, 26)

In [6]:
h = hidden_layer(l,3,np.tanh)

In [7]:
h.forward_prop()

In [8]:
h.get_signal()

array([[ 1.        ],
       [ 0.93712859],
       [-0.43120687],
       [ 0.46105504]])

In [9]:
p = output_layer(h,5,np.tanh)

In [10]:
p.forward_prop()

In [11]:
p.get_signal()

array([[ 0.00559543],
       [ 0.00965738],
       [-0.02041582],
       [-0.00126112],
       [-0.00886366]])

In [12]:
y = parse_csv('train.y.csv',1,2,str)

In [13]:
network = nn(x,enum_classes(y),1e-3)
network2 = nn(x,enum_classes(y),1e-3,13)

In [14]:
network.append_hidden_layer(4, np.tanh)
network2.append_hidden_layer(4, np.tanh)
network.forward_prop()
network2.forward_prop()

In [15]:
network.print_signals()

[[  1.        1.        1.      ...,   1.        1.        1.     ]
 [ 41.08     60.8      51.47    ...,  37.58     38.01     36.23   ]
 [  6.579     5.973     4.971   ...,   5.168     6.073     5.422  ]
 ..., 
 [  0.4075   -1.39      0.02959 ...,  -0.1882   -0.9518   -1.438  ]
 [ -0.6719    0.2256   -0.1367  ...,  -0.1197    0.8782   -1.55   ]
 [ -0.05147  -0.7208    0.1082  ...,   0.05751  -0.5961   -1.502  ]]
[[ 1.          1.          1.         ...,  1.          1.          1.        ]
 [-0.2932472  -0.3036354  -0.25084761 ..., -0.29381566 -0.25906223
  -0.23708209]
 [-0.10469456  0.28240097  0.32937631 ..., -0.09101773  0.04018534
  -0.00969488]
 [-0.78903782 -0.89201995 -0.81432173 ..., -0.73255784 -0.73901227
  -0.73495028]
 [ 0.10568792  0.07498624  0.03387364 ...,  0.12580547 -0.07452682
   0.11590275]]
[[ 0.0753278   0.07507331  0.07515462 ...,  0.07530248  0.07547684
   0.07531874]
 [ 0.07747554  0.07726821  0.07714747 ...,  0.07742864  0.07733818
   0.07732243]
 [ 0.077645

In [16]:
np.sum(network.get_output(), axis=0)

array([ 1.,  1.,  1., ...,  1.,  1.,  1.])

In [17]:
network.calc_end_losses()

In [18]:
network.get_loss()

2.5655600475273315

In [30]:
network.get_output().shape

(13, 13000)

In [23]:
-np.log(1.0/13)

2.5649493574615367