In [1]:
from data_parser import parse_csv, enum_classes
from nn_layers import input_layer, hidden_layer, output_layer
from neural_network import nn, d_tanh, d_cross_entropy_loss
import numpy as np

In [2]:
x = parse_csv('train.x.csv', 1, 27)

In [3]:
y = parse_csv('train.y.csv',1,2,str)

In [4]:
network = nn(x,enum_classes(y))
network.append_hidden_layer(50, np.tanh)
network.forward_prop()

In [5]:
network.get_signals()[0]

array([[  1.00000000e+00,   1.00000000e+00,   1.00000000e+00, ...,
          1.00000000e+00,   1.00000000e+00,   1.00000000e+00],
       [  4.10800000e+01,   6.08000000e+01,   5.14700000e+01, ...,
          3.75800000e+01,   3.80100000e+01,   3.62300000e+01],
       [  6.57900000e+00,   5.97300000e+00,   4.97100000e+00, ...,
          5.16800000e+00,   6.07300000e+00,   5.42200000e+00],
       ..., 
       [  4.07500000e-01,  -1.39000000e+00,   2.95900000e-02, ...,
         -1.88200000e-01,  -9.51800000e-01,  -1.43800000e+00],
       [ -6.71900000e-01,   2.25600000e-01,  -1.36700000e-01, ...,
         -1.19700000e-01,   8.78200000e-01,  -1.55000000e+00],
       [ -5.14700000e-02,  -7.20800000e-01,   1.08200000e-01, ...,
          5.75100000e-02,  -5.96100000e-01,  -1.50200000e+00]])

In [6]:
np.sum(network.get_output(), axis=0)

array([ 1.,  1.,  1., ...,  1.,  1.,  1.])

In [7]:
network.get_output().shape

(13, 13000)

In [8]:
enum_classes(y).shape

(13000,)

In [9]:
network.get_weights()[1]

array([[  1.17776104e-02,  -6.89126911e-03,   8.76240100e-03,
          7.70937884e-03,   6.53109391e-03,   1.85790502e-02,
          1.30811754e-02,  -2.54882445e-03,  -1.85000499e-04,
         -7.33143461e-03,  -6.43478098e-04,   1.01286687e-02,
         -7.78886999e-04],
       [  4.41665959e-03,   6.33060195e-03,  -2.72085296e-03,
          4.93267959e-03,  -1.12357746e-02,  -8.92197536e-03,
         -5.92520663e-04,   2.02927978e-03,   5.34690653e-03,
          4.63349497e-03,   1.13521066e-02,  -1.03870922e-02,
         -1.68216116e-02],
       [ -2.22075258e-02,  -2.24760439e-03,  -3.21917735e-03,
         -7.84431300e-03,  -1.54593313e-02,   5.52069677e-03,
          9.88003432e-03,  -1.45544472e-02,   6.83422240e-03,
          1.68311525e-02,   5.27762999e-03,  -9.51802702e-03,
          5.85859953e-03],
       [ -1.09417570e-03,  -5.29288319e-03,   6.78930951e-03,
          6.09755399e-03,  -6.37756348e-03,   5.12993802e-03,
         -6.99063391e-03,   1.03149308e-02,   1.503

In [10]:
t1 = d_cross_entropy_loss(1,network.get_output(),enum_classes(y))
t2 = network.get_weights()[1]
np.dot(t2,t1).shape

(51, 13000)

In [11]:
d_cross_entropy_loss(1,network.get_output(),enum_classes(y)).shape

(13, 13000)

In [12]:
network.get_signals()[0].shape

(27, 13000)

In [13]:
network.backward_prop()

In [ ]:
network.get_weights()[1]

array([[  1.17882459e-02,  -6.89567930e-03,   8.76908838e-03,
          7.71850780e-03,   6.54079007e-03,   1.86007189e-02,
          1.30887990e-02,  -2.54712327e-03,  -1.90163341e-04,
         -7.32945885e-03,  -6.47970917e-04,   1.01324311e-02,
         -7.79510228e-04],
       [  4.42398200e-03,   6.32777459e-03,  -2.72202503e-03,
          4.94427180e-03,  -1.12515582e-02,  -8.94019229e-03,
         -5.86235378e-04,   2.03313482e-03,   5.33658449e-03,
          4.63971494e-03,   1.13710788e-02,  -1.03859557e-02,
         -1.68403114e-02],
       [ -2.22311624e-02,  -2.24807305e-03,  -3.22332651e-03,
         -7.85121843e-03,  -1.54741689e-02,   5.52782732e-03,
          9.88799455e-03,  -1.45655346e-02,   6.83974329e-03,
          1.68505350e-02,   5.28016861e-03,  -9.53127630e-03,
          5.86555275e-03],
       [ -1.09686369e-03,  -5.29358419e-03,   6.79400524e-03,
          6.10356180e-03,  -6.37980572e-03,   5.13987744e-03,
         -7.00258895e-03,   1.03287444e-02,   1.496

In [ ]:
network.train(1000, 0.05, 1e-7)

Loss for epoch 0 is 2.56660728032671
Loss for epoch 100 is 2.507821943346834
Loss for epoch 200 is 2.4400664581793077
Loss for epoch 300 is 2.418017379292596
Loss for epoch 400 is 2.4106090890909218
Loss for epoch 500 is 2.4117633313715086
Loss for epoch 600 is 2.330955892192476
Loss for epoch 700 is 2.382962937788154
Loss for epoch 800 is 2.3616645042162894
