In [1]:
from data_parser import parse_csv, enum_classes
from nn_layers import input_layer, hidden_layer, output_layer
from neural_network import nn, d_tanh, d_cross_entropy_loss
import numpy as np

In [2]:
x = parse_csv('train.x.csv', 1, 27)

In [3]:
y = parse_csv('train.y.csv',1,2,str)

In [4]:
network = nn(x,enum_classes(y))
network.append_hidden_layer(50, np.tanh)
network.forward_prop()

In [5]:
network.get_signals()[0]

array([[  1.00000000e+00,   1.00000000e+00,   1.00000000e+00, ...,
          1.00000000e+00,   1.00000000e+00,   1.00000000e+00],
       [  4.10800000e+01,   6.08000000e+01,   5.14700000e+01, ...,
          3.75800000e+01,   3.80100000e+01,   3.62300000e+01],
       [  6.57900000e+00,   5.97300000e+00,   4.97100000e+00, ...,
          5.16800000e+00,   6.07300000e+00,   5.42200000e+00],
       ..., 
       [  4.07500000e-01,  -1.39000000e+00,   2.95900000e-02, ...,
         -1.88200000e-01,  -9.51800000e-01,  -1.43800000e+00],
       [ -6.71900000e-01,   2.25600000e-01,  -1.36700000e-01, ...,
         -1.19700000e-01,   8.78200000e-01,  -1.55000000e+00],
       [ -5.14700000e-02,  -7.20800000e-01,   1.08200000e-01, ...,
          5.75100000e-02,  -5.96100000e-01,  -1.50200000e+00]])

In [6]:
np.sum(network.get_output(), axis=0)

array([ 1.,  1.,  1., ...,  1.,  1.,  1.])

In [7]:
network.get_output().shape

(13, 13000)

In [8]:
enum_classes(y).shape

(13000,)

In [9]:
network.get_weights()[1]

array([[  1.78992885e-02,  -1.59833915e-03,  -4.14421363e-03,
         -9.97660866e-03,  -4.02625299e-03,  -1.05640625e-02,
         -1.88489112e-02,   6.51324486e-03,   6.52295824e-03,
         -1.40587793e-02,  -5.93389593e-03,  -5.22945508e-04,
          9.18926169e-04],
       [ -1.98511287e-02,  -2.99319008e-03,  -1.29325999e-02,
         -1.22028808e-02,  -9.46610575e-03,   8.90462386e-03,
          1.78354848e-02,  -1.61061352e-02,   6.20607612e-03,
         -1.49800718e-03,   1.65720617e-02,  -7.65131288e-03,
         -9.81595239e-03],
       [ -8.85174085e-03,   7.80432033e-03,   1.92299422e-03,
         -4.19065336e-03,  -6.39277280e-03,   8.07299703e-04,
          1.82960980e-02,  -6.48194294e-03,  -1.14592089e-02,
          1.54388666e-02,   4.98049598e-04,  -1.51397529e-02,
          1.33614361e-02],
       [  8.83690084e-03,  -1.94851339e-02,  -8.55591755e-03,
         -1.41253888e-02,  -4.17970563e-03,  -5.35352225e-03,
          9.15414793e-04,  -1.12353641e-02,   2.711

In [10]:
t1 = d_cross_entropy_loss(1,network.get_output(),enum_classes(y))
t2 = network.get_weights()[1]
np.dot(t2,t1).shape

(51, 13000)

In [11]:
d_cross_entropy_loss(1,network.get_output(),enum_classes(y)).shape

(13, 13000)

In [12]:
network.get_signals()[0].shape

(27, 13000)

In [13]:
network.backward_prop()

In [14]:
network.get_weights()[1]

array([[  1.79077993e-02,  -1.60035344e-03,  -4.14381975e-03,
         -9.98222001e-03,  -4.03718298e-03,  -1.05693183e-02,
         -1.88683548e-02,   6.51111260e-03,   6.52646646e-03,
         -1.40625161e-02,  -5.93974561e-03,  -5.20884111e-04,
          9.21605994e-04],
       [ -1.98741536e-02,  -2.99762450e-03,  -1.29497851e-02,
         -1.22186725e-02,  -9.47814457e-03,   8.91483455e-03,
          1.78512463e-02,  -1.61287241e-02,   6.20882681e-03,
         -1.49291535e-03,   1.65930799e-02,  -7.65006225e-03,
         -9.81997109e-03],
       [ -8.85135379e-03,   7.81261928e-03,   1.92059994e-03,
         -4.19872750e-03,  -6.39229878e-03,   8.02935103e-04,
          1.83151108e-02,  -6.47994029e-03,  -1.14675733e-02,
          1.54439454e-02,   4.98267759e-04,  -1.51577391e-02,
          1.33727603e-02],
       [  8.84181402e-03,  -1.95056880e-02,  -8.56273775e-03,
         -1.41383025e-02,  -4.18746551e-03,  -5.35678613e-03,
          9.15756854e-04,  -1.12502358e-02,   2.713

In [15]:
network.train(10000, 0.01, 1e-7, 10)
network.log_loss()

Loss for epoch 0 is 2.5809695491499456
Loss for epoch 200 is 2.1909827519307603
Loss for epoch 400 is 2.177621900229158
Loss for epoch 600 is 2.1730787029063556
Loss for epoch 800 is 2.170797720865674
Loss for epoch 1000 is 2.169427840936334
Loss for epoch 1200 is 2.1685146951979837
Loss for epoch 1400 is 2.146612160283794
Loss for epoch 1600 is 2.009864862809208
Loss for epoch 1800 is 1.9386262574277136
Loss for epoch 2000 is 2.085685687795499
Loss for epoch 2200 is 1.7439491484223923
Loss for epoch 2400 is 1.451082586795423
Loss for epoch 2600 is 1.1857783252704617
Loss for epoch 2800 is 1.235293503706637
Loss for epoch 3000 is 1.1365582455939263
Loss for epoch 3200 is 0.9385500765303028
Loss for epoch 3400 is 0.7463086514239375
Loss for epoch 3600 is 0.6899272757129638
Loss for epoch 3800 is 0.5094740640179567
Loss for epoch 4000 is 0.3098036007895581
Loss for epoch 4200 is 0.2380140062079888
Loss for epoch 4400 is 0.18580333983792993
Loss for epoch 4600 is 0.1463352402830545
Loss f

0.01698250998930999